# Generated by Django 3.1.7 on 2021-06-24 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('role', models.CharField(choices=[('STANDARD', 'Basic employee'), ('HR', 'Human resources'), ('SUPERVISOR', 'Supervisor'), ('MANAGER', 'Manager'), ('PRESIDENT', 'President')], default='STANDARD', max_length=50)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hr.person')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_employees', to='hr.employee')),
            ],
        ),
    ]
