# Generated by Django 3.1.7 on 2021-06-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_person_frinds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='frinds',
        ),
        migrations.AddField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(related_name='_person_friends_+', to='hr.Person'),
        ),
    ]
