# Generated by Django 3.1.7 on 2021-09-09 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0003_auto_20210908_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='parent_key_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_objective', to='okr.keyresult'),
        ),
    ]
