# Generated by Django 3.1.7 on 2021-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20210628_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, upload_to='artist/'),
        ),
    ]
