# Generated by Django 3.1.7 on 2021-07-06 23:25

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_feat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='feat',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(songs.models.get_unkown_artist), related_name='songs_featured', to='songs.artist'),
        ),
    ]
