# Generated by Django 3.1.7 on 2021-07-02 01:19

from django.db import migrations, models
import utils.validators.numbers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[utils.validators.numbers.validate_integer, utils.validators.numbers.validate_non_negative])),
                ('odd', models.IntegerField(validators=[utils.validators.numbers.validate_integer, utils.validators.numbers.validate_non_negative, utils.validators.numbers.validate_odd])),
                ('even', models.IntegerField(validators=[utils.validators.numbers.validate_integer, utils.validators.numbers.validate_non_negative, utils.validators.numbers.validate_even])),
            ],
        ),
    ]
